type: lib
language: xp
description: Create an XP api client project with Maven support.

partials:
  - general/readme
  - general/makefile
  - xp/maven
  - xp/projectpth
  - xp/unittest
  - xp/integrationtest

defaults:
  - name: users-api-client
  - groupId: org.mycompany.lib

checks:
  - git
  - jenkins
  - tests/unittest
  - tests/integrationtests
