type: automation
language: python
description: Create a Fabric project for automatic installation and deployment of services.

partials:
  - general/readme
  - python/config

checks:
  - git
  - jenkins
  - tests/unittest
