description: Create an XP api client project with Maven support.

partials:
  - general/readme
  - general/makefile
  - partials/xp-maven
  - partials/xp-projectpth
  - partials/xp-unittest
  - partials/xp-integrationtest

variables:
  - name: users-api-client
  - groupId: org.mycompany.lib
