description: Create an XP backend project with Maven support.

partials:
  - general/readme
  - general/makefile
  - partials/xp-maven
  - partials/xp-projectpth
  - partials/xp-config
  - partials/xp-unittest
  
optionalPartials:
  - partials/xp-cron
  - partials/xp-supervisord

variables:
  - groupId: org.mycompany.app
  - xpInstallStage: dev
  - xpInstallProd: high
